spring:
  profiles:
    - application.properties
  datasource:

    druid:

      url: jdbc:mysql://ip:port/dbname?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: hauwei@123
      initial-size: 1
      min-idle: "${druid.}"

      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver

      driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: huawei.sample.entity
  mapper-locations: classpath:mapper/*.xml